n = str (input ("digite o seu nome completo :")).strip()
nome = n.split()
print("Muito prazer em te conhecer")
print("seu primeiro nome é {}".format(nome[0]))
print("E seu ultimo nome é {}".format(nome[len(nome)-1]))
