valor = float(input("qual o valore do imovél desejado R$ ?"))
sal = float (input("qual é seu salário mensal R$ ?"))
anos = int(input("em até quantos anos você deseja pagar ?"))
presta = valor / (anos * 12)
print("valor {}".format(presta))